export const Data =[
    {
        id:1,
        name:'Faizan',
        catagory:'Student',
        section:'BSSE7',
    },
    {
        id:2,
        name:'Shakeel',
        catagory:'Adminstration',
        section:'BSSE7',
    },
    {
        id:3,
        name:'Manan',
        catagory:'Chaprasi',
        section:'BSSE7',
    },
    {
        id:4,
        name:'Yassaar',
        catagory:'Chaprasi',
        section:'BSSE7',
    },
]